//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PrilozhenieIspravl
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// График матчей.
    /// </summary>
    // *** Start programmer edit section *** (ГрафикМатчей CustomAttributes)

    // *** End programmer edit section *** (ГрафикМатчей CustomAttributes)
    [AutoAltered()]
    [Caption("График матчей")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГрафикМатчейE", new string[] {
            "ДатаСоздания as \'Дата создания\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Сотрудники.ФИО"})]
    [AssociatedDetailViewAttribute("ГрафикМатчейE", "ТЧГрафика", "ТЧГрафикаE", true, "", "Т ч графика", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ГрафикМатчейE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ГрафикМатчейL", new string[] {
            "ДатаСоздания as \'Дата создания\'",
            "Сотрудники.ФИО as \'ФИО\'"})]
    public class ГрафикМатчей : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаСоздания = System.DateTime.Now;
        
        private IIS.PrilozhenieIspravl.Сотрудники fСотрудники;
        
        private IIS.PrilozhenieIspravl.DetailArrayOfТЧГрафика fТЧГрафика;
        
        // *** Start programmer edit section *** (ГрафикМатчей CustomMembers)

        // *** End programmer edit section *** (ГрафикМатчей CustomMembers)

        
        /// <summary>
        /// ДатаСоздания.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикМатчей.ДатаСоздания CustomAttributes)

        // *** End programmer edit section *** (ГрафикМатчей.ДатаСоздания CustomAttributes)
        public virtual System.DateTime ДатаСоздания
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикМатчей.ДатаСоздания Get start)

                // *** End programmer edit section *** (ГрафикМатчей.ДатаСоздания Get start)
                System.DateTime result = this.fДатаСоздания;
                // *** Start programmer edit section *** (ГрафикМатчей.ДатаСоздания Get end)

                // *** End programmer edit section *** (ГрафикМатчей.ДатаСоздания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикМатчей.ДатаСоздания Set start)

                // *** End programmer edit section *** (ГрафикМатчей.ДатаСоздания Set start)
                this.fДатаСоздания = value;
                // *** Start programmer edit section *** (ГрафикМатчей.ДатаСоздания Set end)

                // *** End programmer edit section *** (ГрафикМатчей.ДатаСоздания Set end)
            }
        }
        
        /// <summary>
        /// График матчей.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикМатчей.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ГрафикМатчей.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.PrilozhenieIspravl.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикМатчей.Сотрудники Get start)

                // *** End programmer edit section *** (ГрафикМатчей.Сотрудники Get start)
                IIS.PrilozhenieIspravl.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ГрафикМатчей.Сотрудники Get end)

                // *** End programmer edit section *** (ГрафикМатчей.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикМатчей.Сотрудники Set start)

                // *** End programmer edit section *** (ГрафикМатчей.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ГрафикМатчей.Сотрудники Set end)

                // *** End programmer edit section *** (ГрафикМатчей.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// График матчей.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикМатчей.ТЧГрафика CustomAttributes)

        // *** End programmer edit section *** (ГрафикМатчей.ТЧГрафика CustomAttributes)
        public virtual IIS.PrilozhenieIspravl.DetailArrayOfТЧГрафика ТЧГрафика
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикМатчей.ТЧГрафика Get start)

                // *** End programmer edit section *** (ГрафикМатчей.ТЧГрафика Get start)
                if ((this.fТЧГрафика == null))
                {
                    this.fТЧГрафика = new IIS.PrilozhenieIspravl.DetailArrayOfТЧГрафика(this);
                }
                IIS.PrilozhenieIspravl.DetailArrayOfТЧГрафика result = this.fТЧГрафика;
                // *** Start programmer edit section *** (ГрафикМатчей.ТЧГрафика Get end)

                // *** End programmer edit section *** (ГрафикМатчей.ТЧГрафика Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикМатчей.ТЧГрафика Set start)

                // *** End programmer edit section *** (ГрафикМатчей.ТЧГрафика Set start)
                this.fТЧГрафика = value;
                // *** Start programmer edit section *** (ГрафикМатчей.ТЧГрафика Set end)

                // *** End programmer edit section *** (ГрафикМатчей.ТЧГрафика Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГрафикМатчейE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГрафикМатчейE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГрафикМатчейE", typeof(IIS.PrilozhenieIspravl.ГрафикМатчей));
                }
            }
            
            /// <summary>
            /// "ГрафикМатчейL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГрафикМатчейL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГрафикМатчейL", typeof(IIS.PrilozhenieIspravl.ГрафикМатчей));
                }
            }
        }
    }
}
