//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PrilozhenieIspravl
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Группы возраст.
    /// </summary>
    // *** Start programmer edit section *** (ГруппыВозраст CustomAttributes)

    // *** End programmer edit section *** (ГруппыВозраст CustomAttributes)
    [AutoAltered()]
    [Caption("Группы возраст")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГруппыВозрастE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("ГруппыВозрастL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class ГруппыВозраст : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (ГруппыВозраст CustomMembers)

        // *** End programmer edit section *** (ГруппыВозраст CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ГруппыВозраст.Наименование CustomAttributes)

        // *** End programmer edit section *** (ГруппыВозраст.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ГруппыВозраст.Наименование Get start)

                // *** End programmer edit section *** (ГруппыВозраст.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ГруппыВозраст.Наименование Get end)

                // *** End programmer edit section *** (ГруппыВозраст.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГруппыВозраст.Наименование Set start)

                // *** End programmer edit section *** (ГруппыВозраст.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ГруппыВозраст.Наименование Set end)

                // *** End programmer edit section *** (ГруппыВозраст.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГруппыВозрастE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГруппыВозрастE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГруппыВозрастE", typeof(IIS.PrilozhenieIspravl.ГруппыВозраст));
                }
            }
            
            /// <summary>
            /// "ГруппыВозрастL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГруппыВозрастL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГруппыВозрастL", typeof(IIS.PrilozhenieIspravl.ГруппыВозраст));
                }
            }
        }
    }
}
