//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PrilozhenieIspravl
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Место проведения.
    /// </summary>
    // *** Start programmer edit section *** (МестоПроведения CustomAttributes)

    // *** End programmer edit section *** (МестоПроведения CustomAttributes)
    [AutoAltered()]
    [Caption("Место проведения")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МестоПроведенияE", new string[] {
            "Наименование as \'Наименование\'",
            "Адрес as \'Адрес\'"})]
    [View("МестоПроведенияL", new string[] {
            "Наименование as \'Наименование\'",
            "Адрес as \'Адрес\'"})]
    public class МестоПроведения : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private string fАдрес;
        
        // *** Start programmer edit section *** (МестоПроведения CustomMembers)

        // *** End programmer edit section *** (МестоПроведения CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (МестоПроведения.Адрес CustomAttributes)

        // *** End programmer edit section *** (МестоПроведения.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (МестоПроведения.Адрес Get start)

                // *** End programmer edit section *** (МестоПроведения.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (МестоПроведения.Адрес Get end)

                // *** End programmer edit section *** (МестоПроведения.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (МестоПроведения.Адрес Set start)

                // *** End programmer edit section *** (МестоПроведения.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (МестоПроведения.Адрес Set end)

                // *** End programmer edit section *** (МестоПроведения.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (МестоПроведения.Наименование CustomAttributes)

        // *** End programmer edit section *** (МестоПроведения.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (МестоПроведения.Наименование Get start)

                // *** End programmer edit section *** (МестоПроведения.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (МестоПроведения.Наименование Get end)

                // *** End programmer edit section *** (МестоПроведения.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (МестоПроведения.Наименование Set start)

                // *** End programmer edit section *** (МестоПроведения.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (МестоПроведения.Наименование Set end)

                // *** End programmer edit section *** (МестоПроведения.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МестоПроведенияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МестоПроведенияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МестоПроведенияE", typeof(IIS.PrilozhenieIspravl.МестоПроведения));
                }
            }
            
            /// <summary>
            /// "МестоПроведенияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МестоПроведенияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МестоПроведенияL", typeof(IIS.PrilozhenieIspravl.МестоПроведения));
                }
            }
        }
    }
}
