//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PrilozhenieIspravl
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состав команды.
    /// </summary>
    // *** Start programmer edit section *** (СоставКоманды CustomAttributes)

    // *** End programmer edit section *** (СоставКоманды CustomAttributes)
    [AutoAltered()]
    [Caption("Состав команды")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СоставКомандыE", new string[] {
            "ИмяКоманды as \'Имя команды\'",
            "ГруппыВозраст as \'Группы возраст\'",
            "ГруппыВозраст.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "ГруппыВозраст.Наименование"})]
    [AssociatedDetailViewAttribute("СоставКомандыE", "ТЧСоставаТренер", "ТЧСоставаТренерE", true, "", "Т ч состава тренер", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("СоставКомандыE", "ТЧСоставСпорт", "ТЧСоставСпортE", true, "", "Т ч состав спорт", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("СоставКомандыE", "ГруппыВозраст", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("СоставКомандыL", new string[] {
            "ИмяКоманды as \'Имя команды\'",
            "ГруппыВозраст.Наименование as \'Наименование\'"})]
    public class СоставКоманды : ICSSoft.STORMNET.DataObject
    {
        
        private string fИмяКоманды;
        
        private IIS.PrilozhenieIspravl.ГруппыВозраст fГруппыВозраст;
        
        private IIS.PrilozhenieIspravl.Сотрудники fСотрудники;
        
        private IIS.PrilozhenieIspravl.DetailArrayOfТЧСоставаТренер fТЧСоставаТренер;
        
        private IIS.PrilozhenieIspravl.DetailArrayOfТЧСоставСпорт fТЧСоставСпорт;
        
        // *** Start programmer edit section *** (СоставКоманды CustomMembers)

        // *** End programmer edit section *** (СоставКоманды CustomMembers)

        
        /// <summary>
        /// ИмяКоманды.
        /// </summary>
        // *** Start programmer edit section *** (СоставКоманды.ИмяКоманды CustomAttributes)

        // *** End programmer edit section *** (СоставКоманды.ИмяКоманды CustomAttributes)
        [StrLen(255)]
        public virtual string ИмяКоманды
        {
            get
            {
                // *** Start programmer edit section *** (СоставКоманды.ИмяКоманды Get start)

                // *** End programmer edit section *** (СоставКоманды.ИмяКоманды Get start)
                string result = this.fИмяКоманды;
                // *** Start programmer edit section *** (СоставКоманды.ИмяКоманды Get end)

                // *** End programmer edit section *** (СоставКоманды.ИмяКоманды Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставКоманды.ИмяКоманды Set start)

                // *** End programmer edit section *** (СоставКоманды.ИмяКоманды Set start)
                this.fИмяКоманды = value;
                // *** Start programmer edit section *** (СоставКоманды.ИмяКоманды Set end)

                // *** End programmer edit section *** (СоставКоманды.ИмяКоманды Set end)
            }
        }
        
        /// <summary>
        /// Состав команды.
        /// </summary>
        // *** Start programmer edit section *** (СоставКоманды.ГруппыВозраст CustomAttributes)

        // *** End programmer edit section *** (СоставКоманды.ГруппыВозраст CustomAttributes)
        [PropertyStorage(new string[] {
                "ГруппыВозраст"})]
        [NotNull()]
        public virtual IIS.PrilozhenieIspravl.ГруппыВозраст ГруппыВозраст
        {
            get
            {
                // *** Start programmer edit section *** (СоставКоманды.ГруппыВозраст Get start)

                // *** End programmer edit section *** (СоставКоманды.ГруппыВозраст Get start)
                IIS.PrilozhenieIspravl.ГруппыВозраст result = this.fГруппыВозраст;
                // *** Start programmer edit section *** (СоставКоманды.ГруппыВозраст Get end)

                // *** End programmer edit section *** (СоставКоманды.ГруппыВозраст Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставКоманды.ГруппыВозраст Set start)

                // *** End programmer edit section *** (СоставКоманды.ГруппыВозраст Set start)
                this.fГруппыВозраст = value;
                // *** Start programmer edit section *** (СоставКоманды.ГруппыВозраст Set end)

                // *** End programmer edit section *** (СоставКоманды.ГруппыВозраст Set end)
            }
        }
        
        /// <summary>
        /// Состав команды.
        /// </summary>
        // *** Start programmer edit section *** (СоставКоманды.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (СоставКоманды.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.PrilozhenieIspravl.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (СоставКоманды.Сотрудники Get start)

                // *** End programmer edit section *** (СоставКоманды.Сотрудники Get start)
                IIS.PrilozhenieIspravl.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (СоставКоманды.Сотрудники Get end)

                // *** End programmer edit section *** (СоставКоманды.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставКоманды.Сотрудники Set start)

                // *** End programmer edit section *** (СоставКоманды.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (СоставКоманды.Сотрудники Set end)

                // *** End programmer edit section *** (СоставКоманды.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Состав команды.
        /// </summary>
        // *** Start programmer edit section *** (СоставКоманды.ТЧСоставаТренер CustomAttributes)

        // *** End programmer edit section *** (СоставКоманды.ТЧСоставаТренер CustomAttributes)
        public virtual IIS.PrilozhenieIspravl.DetailArrayOfТЧСоставаТренер ТЧСоставаТренер
        {
            get
            {
                // *** Start programmer edit section *** (СоставКоманды.ТЧСоставаТренер Get start)

                // *** End programmer edit section *** (СоставКоманды.ТЧСоставаТренер Get start)
                if ((this.fТЧСоставаТренер == null))
                {
                    this.fТЧСоставаТренер = new IIS.PrilozhenieIspravl.DetailArrayOfТЧСоставаТренер(this);
                }
                IIS.PrilozhenieIspravl.DetailArrayOfТЧСоставаТренер result = this.fТЧСоставаТренер;
                // *** Start programmer edit section *** (СоставКоманды.ТЧСоставаТренер Get end)

                // *** End programmer edit section *** (СоставКоманды.ТЧСоставаТренер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставКоманды.ТЧСоставаТренер Set start)

                // *** End programmer edit section *** (СоставКоманды.ТЧСоставаТренер Set start)
                this.fТЧСоставаТренер = value;
                // *** Start programmer edit section *** (СоставКоманды.ТЧСоставаТренер Set end)

                // *** End programmer edit section *** (СоставКоманды.ТЧСоставаТренер Set end)
            }
        }
        
        /// <summary>
        /// Состав команды.
        /// </summary>
        // *** Start programmer edit section *** (СоставКоманды.ТЧСоставСпорт CustomAttributes)

        // *** End programmer edit section *** (СоставКоманды.ТЧСоставСпорт CustomAttributes)
        public virtual IIS.PrilozhenieIspravl.DetailArrayOfТЧСоставСпорт ТЧСоставСпорт
        {
            get
            {
                // *** Start programmer edit section *** (СоставКоманды.ТЧСоставСпорт Get start)

                // *** End programmer edit section *** (СоставКоманды.ТЧСоставСпорт Get start)
                if ((this.fТЧСоставСпорт == null))
                {
                    this.fТЧСоставСпорт = new IIS.PrilozhenieIspravl.DetailArrayOfТЧСоставСпорт(this);
                }
                IIS.PrilozhenieIspravl.DetailArrayOfТЧСоставСпорт result = this.fТЧСоставСпорт;
                // *** Start programmer edit section *** (СоставКоманды.ТЧСоставСпорт Get end)

                // *** End programmer edit section *** (СоставКоманды.ТЧСоставСпорт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставКоманды.ТЧСоставСпорт Set start)

                // *** End programmer edit section *** (СоставКоманды.ТЧСоставСпорт Set start)
                this.fТЧСоставСпорт = value;
                // *** Start programmer edit section *** (СоставКоманды.ТЧСоставСпорт Set end)

                // *** End programmer edit section *** (СоставКоманды.ТЧСоставСпорт Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СоставКомандыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СоставКомандыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СоставКомандыE", typeof(IIS.PrilozhenieIspravl.СоставКоманды));
                }
            }
            
            /// <summary>
            /// "СоставКомандыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СоставКомандыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СоставКомандыL", typeof(IIS.PrilozhenieIspravl.СоставКоманды));
                }
            }
        }
    }
}
