//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PrilozhenieIspravl
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч состав спорт.
    /// </summary>
    // *** Start programmer edit section *** (ТЧСоставСпорт CustomAttributes)

    // *** End programmer edit section *** (ТЧСоставСпорт CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч состав спорт")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧСоставСпортE", new string[] {
            "Спортсмены as \'Спортсмены\'",
            "Спортсмены.ФИО as \'ФИО\'",
            "НомерСпортсмена as \'Номер спортсмена\'",
            "Спортсмены.ДатаРождения as \'Дата рождения\'"}, Hidden=new string[] {
            "Спортсмены.ФИО"})]
    [MasterViewDefineAttribute("ТЧСоставСпортE", "Спортсмены", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    public class ТЧСоставСпорт : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерСпортсмена;
        
        private IIS.PrilozhenieIspravl.Спортсмены fСпортсмены;
        
        private IIS.PrilozhenieIspravl.СоставКоманды fСоставКоманды;
        
        // *** Start programmer edit section *** (ТЧСоставСпорт CustomMembers)

        // *** End programmer edit section *** (ТЧСоставСпорт CustomMembers)

        
        /// <summary>
        /// НомерСпортсмена.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСоставСпорт.НомерСпортсмена CustomAttributes)

        // *** End programmer edit section *** (ТЧСоставСпорт.НомерСпортсмена CustomAttributes)
        public virtual int НомерСпортсмена
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСоставСпорт.НомерСпортсмена Get start)

                // *** End programmer edit section *** (ТЧСоставСпорт.НомерСпортсмена Get start)
                int result = this.fНомерСпортсмена;
                // *** Start programmer edit section *** (ТЧСоставСпорт.НомерСпортсмена Get end)

                // *** End programmer edit section *** (ТЧСоставСпорт.НомерСпортсмена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСоставСпорт.НомерСпортсмена Set start)

                // *** End programmer edit section *** (ТЧСоставСпорт.НомерСпортсмена Set start)
                this.fНомерСпортсмена = value;
                // *** Start programmer edit section *** (ТЧСоставСпорт.НомерСпортсмена Set end)

                // *** End programmer edit section *** (ТЧСоставСпорт.НомерСпортсмена Set end)
            }
        }
        
        /// <summary>
        /// Т ч состав спорт.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСоставСпорт.Спортсмены CustomAttributes)

        // *** End programmer edit section *** (ТЧСоставСпорт.Спортсмены CustomAttributes)
        [PropertyStorage(new string[] {
                "Спортсмены"})]
        [NotNull()]
        public virtual IIS.PrilozhenieIspravl.Спортсмены Спортсмены
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСоставСпорт.Спортсмены Get start)

                // *** End programmer edit section *** (ТЧСоставСпорт.Спортсмены Get start)
                IIS.PrilozhenieIspravl.Спортсмены result = this.fСпортсмены;
                // *** Start programmer edit section *** (ТЧСоставСпорт.Спортсмены Get end)

                // *** End programmer edit section *** (ТЧСоставСпорт.Спортсмены Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСоставСпорт.Спортсмены Set start)

                // *** End programmer edit section *** (ТЧСоставСпорт.Спортсмены Set start)
                this.fСпортсмены = value;
                // *** Start programmer edit section *** (ТЧСоставСпорт.Спортсмены Set end)

                // *** End programmer edit section *** (ТЧСоставСпорт.Спортсмены Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.PrilozhenieIspravl.СоставКоманды.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСоставСпорт.СоставКоманды CustomAttributes)

        // *** End programmer edit section *** (ТЧСоставСпорт.СоставКоманды CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "СоставКоманды"})]
        public virtual IIS.PrilozhenieIspravl.СоставКоманды СоставКоманды
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСоставСпорт.СоставКоманды Get start)

                // *** End programmer edit section *** (ТЧСоставСпорт.СоставКоманды Get start)
                IIS.PrilozhenieIspravl.СоставКоманды result = this.fСоставКоманды;
                // *** Start programmer edit section *** (ТЧСоставСпорт.СоставКоманды Get end)

                // *** End programmer edit section *** (ТЧСоставСпорт.СоставКоманды Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСоставСпорт.СоставКоманды Set start)

                // *** End programmer edit section *** (ТЧСоставСпорт.СоставКоманды Set start)
                this.fСоставКоманды = value;
                // *** Start programmer edit section *** (ТЧСоставСпорт.СоставКоманды Set end)

                // *** End programmer edit section *** (ТЧСоставСпорт.СоставКоманды Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧСоставСпортE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧСоставСпортE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧСоставСпортE", typeof(IIS.PrilozhenieIspravl.ТЧСоставСпорт));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧСоставСпорт.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧСоставСпорт CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧСоставСпорт CustomAttributes)
    public class DetailArrayOfТЧСоставСпорт : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.PrilozhenieIspravl.DetailArrayOfТЧСоставСпорт members)

        // *** End programmer edit section *** (IIS.PrilozhenieIspravl.DetailArrayOfТЧСоставСпорт members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧСоставСпорт by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧСоставСпорт.
        /// </summary>
        public DetailArrayOfТЧСоставСпорт(IIS.PrilozhenieIspravl.СоставКоманды fСоставКоманды) : 
                base(typeof(ТЧСоставСпорт), ((ICSSoft.STORMNET.DataObject)(fСоставКоманды)))
        {
        }
        
        public IIS.PrilozhenieIspravl.ТЧСоставСпорт this[int index]
        {
            get
            {
                return ((IIS.PrilozhenieIspravl.ТЧСоставСпорт)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.PrilozhenieIspravl.ТЧСоставСпорт dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
